[build]
builder = "nixpacks"
buildCommand = "npm install && npx prisma generate && npx prisma db push && npm run build"

[deploy]
startCommand = "npm run start"
restartPolicyType = "on_failure"
healthcheckPath = "/"
healthcheckTimeout = 30

[phases.setup]
nixPkgs = ["nodejs_20", "npm-10_x"]

[[volumes]]
mountPath = "/data"
